spring:
  application:
    name: RupaliConstBackend

  datasource:
    url: jdbc:postgresql://db.vnnfkxlajvneogytyrxe.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: admin@rupali123
    driver-class-name: org.postgresql.Driver
  jmx:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
